### PR TITLE
[STUDIO-4785] upgrade geckodriver v0.34.0

### PR DESCRIPTION
**Pull request by TriLeKatalon**
## Content
Follow this document: https://katalon.atlassian.net/wiki/spaces/TEAM/pages/938606949/How+to+update+gecko-releases.json+on+katalon-studio
- Remove content of mac M1 because KS hasn’t supported mac M1 yet. Please refer to: [Temporary remove support for Mac M1 · katalon-studio/katalon-studio@0081e23](https://github.com/katalon-studio/katalon-studio/commit/0081e232638f8491b76efc1074b432714dda425e)
- Remove the content of win aarch64 and linux aarch64. Please refer to:  [Remove win-aarch64](https://github.com/katalon-studio/katalon-studio/pull/603) & [Remove gecko linux aarch64](https://github.com/katalon-studio/katalon-studio/pull/604)
## Ticket references
- [STUDIO-4785](https://katalon.atlassian.net/browse/STUDIO-4785)
## Checklist
- [x] Check base branch
- [x] All requirements are read and clear
- [x] Tested by Dev field were input
- [x] Verify all code changes are formatted
- [ ] Review SonarCloud code quality report

[STUDIO-4785]: https://katalon.atlassian.net/browse/STUDIO-4785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by linhtnlK** [comment]
@nghiadhd-2702 , Do we support for mac M1 ?

**Comment by nghiadhd-2702** [comment]
> @nghiadhd-2702 , Do we support for mac M1 ?

Yes, sure. We support Apple Silicon chip too

**Comment by TriLeKatalon** [comment]
> > @nghiadhd-2702 , Do we support for mac M1 ?
> 
> Yes, sure. We support Apple Silicon chip too

Thanks, I have updated in code and the document as well https://katalon.atlassian.net/wiki/spaces/TEAM/pages/938606949/How+to+update+gecko-releases.json+on+katalon-studio

**Comment by linhtnlK** [comment]
Sorry a @nghiadhd-2702. We've not supported upgrading the drivers for Mac chip M. However, if we do it on this PR, it will impact other drivers (Chrome. Edge Chromium, and  Edge). We should create another ticket to handle it.
Depending on a Nghĩa decision, revert the last commit or spend more effort to do a @TriLeKatalon :3 
[WebDriverManager docs](https://bonigarcia.dev/webdrivermanager/)
image
image

**Comment by TriLeKatalon** [comment]
> Sorry a @nghiadhd-2702. We've not supported upgrading the drivers for Mac chip M. However, if we do it on this PR, it will impact other drivers (Chrome. Edge Chromium, and Edge). We should create another ticket to handle it. Depending on a Nghĩa decision, revert the last commit or spend more effort to do a @TriLeKatalon :3 [WebDriverManager docs](https://bonigarcia.dev/webdrivermanager/) image image

As the urgency, I would like to revert the last commit.

**Review by linhtnlK — APPROVED** [review]

**Pull request merged**
